### ISSUE TITLE
Spoke architecture meta ticket

### ISSUE THREAD

**Issue by bchrobot** [politics-rewired/Spoke#1233]
This ticket will serve as a brainstorming thread for potential changes to Spoke Rewired architecture to pursue and associated changes required to the codebase.

**Comment by bchrobot** [comment]
### Split Front-end Back-end

**Problem**

Currently, the Spoke API server also serves the backend as dynamic content. This is a bad use of CPU and leads to ugly 502 and 503 nginx pages whenever the API service is unavailable.

**Proposed Solution**

Split front-end and back end code and serve front-end application from CDN

Changes to application:
- Move `window.` variables into `SpokeContext`, fetched from the API
- Refactor codebase to clearly separate front-end application, back-end application, and libraries

Changes to build process:
- Front-end application built and shipped to CDN
- Back-end continues to be built as Docker image and pushed to GAR

Open questions:
- [ ] How should front end application discover API server's base URL? A few options:
    - Distinct SPA applications for each client; API server base URL set during build
    - Inject base URL at serve-time. For example, serving static assets via a lightweight nginx setup that does a web application -> api server base URL lookup and injection and then heavy caching

**Comment by bchrobot** [comment]
### Serverless API Service

**Problem**

Spoke on Kubernetes requires separate deployments for each client. This leads to poor utilization of resources. It also complicates scaling behavior.

**Proposed Solution**

Look into server-less function-as-a-service (FaaS) for backend. This

Considerations:
- [ ] How are long-running requests handled? Do we have limited execution time?
- [ ] How do we handle graphile worker? Should workers continue to run in Kubernetes? Can we rig a polling function to kick off batches of worker processing?
- [ ] Can we use container images + firecracker? Or would we need to change our back-end application build process?

**Comment by bchrobot** [comment]
### Redis

**Problem**

We're not utilizing caching for the majority of clients.

**Proposed Solution**

Audit the various Redis (three, I think?) in Spoke, standardize on one, widely deploy.

**Comment by ben-pr-p** [comment]
# Front End / Back End

Fully static serving sounds good to me, but an intermediate solution that might be a bit easier to roll out and would still let us do rollbacks of the client from Kubernetes would be:
- Serve `index.html` only from the server, which sets `window.X` variables and requests the bundle
- Host versioned bundles in a single bucket / CDN ( `client-bundles.spoke-rewired.com` ) which `index.html` can request

This lets us serve the vast majority of the static data from a bucket / CDN while letting us roll back the client quickly and without dropping our `window.X` approach.

# Serverless API Service (FaaS):

> Long running functions can be handled by Google Cloud Tasks, graphile worker supports exporting tasks to Google Cloud Tasks https://github.com/graphile/worker/blob/main/examples/worker-cloud-tasks-exporter/README.md

Just pointing out that this is just a Graphile Worker job to move to Google Cloud tasks, but something still needs to be running all the time to send the tasks to Google Cloud Tasks.

I think in order to move to fully serverless task execution, we'd need to move task queueing to directly run on Google Cloud tasks, which means removing any queueing from within the database (or somehow making sure that before exiting, the server cleared any tasks and sent them to Cloud Tasks).

Cloud Run could be a good intermediate solution that:
- Doesn't require us building a new container
- Doesn't have any execution limits
- Supports better autoscaling than Kubernetes: it supports scaling per concurrent request (which we'd set to some thing close to the container pool size) instead of CPU / memory resources.

Cloud Run would let us get scale to zero and better autoscaling behavior, but we'd still need to figure out to make sure tasks wake up the instance, if needed. I think the only tasks that wouldn't be completed within Cloud Run's 15 minute shut down grace period are cron jobs, which we could move to Google Scheduler.

The other benefit of Cloud Run is we have greater transparency into instance size and count, which means we have better control of database connection usage, which given the way we use databases is a concern. If we want to use PgBouncer though, that'd be great and probably good and helpful either way.

Cloud Run is probably costlier and scales a bit worse than Functions / Lambdas in the long run though, I think!

**Comment by bchrobot** [comment]
# Redis

## Uses
- better rate limiting in graphile-worker (no named queues)
- caching login sessions (1-2 fewer PG calls per API request)
- storing things that don't change very frequently (spoke context, organization data, etc.)

## Implementation
- In practice, caching for larger campaigns ended up being ~500mb
- Difficult to manage HA Redis on k8s? Use GCP Redis?
- If per-client Redis namespaces are an option, can use one global (autoscaling?) instance (GCP or K8s)?
- KeyDB: Redis clone with active-active support -- maybe worth looking into
- Currently:
    - Memoredis
    - thinky Redis support

## Next Steps
- [ ] Audit of what we are and are not caching
- [ ] General cache strategy -- playbook for code changes / code reviews. Key name, key namespaces, etc.
    - [ ] How does caching strategy interact with Retool? Does Retool have Redis resource we can add to Retool environment declarations and use in Retool apps?
- [ ] Add it!

**Comment by bchrobot** [comment]
# PG

Should we move to Google Cloud SQL?

- [ ] What client replication options does Google Cloud SQL support?
- [ ] What are our costs on Zalando?
- [ ] What does the transition to Google Cloud SQL look like? How does that work for new/old clients? (path to GC SQL is different from path to not using Zalando)
    - [Google's Docs on DMS](https://cloud.google.com/database-migration)
- [ ] Do we want to rebalance clients?
- [ ] Scale up behavior/timing for scaling changes (with or without HA [and associated cost])

**Comment by bchrobot** [comment]
# Backend

## Short term
- [ ] K8s resource tuning (pods + node pools)

## Serverless?
- [ ] Task management - how to manage scheduling (specifically auto-sending)

**Comment by ben-pr-p** [comment]
Another problem to be solved with our serverless / back-end choice is autoscaling - right now, our HPA's only autoscale based on RAM / CPU, but we'd probably actually want to scale based on number of requests per instance, which is tightly related to pool and concurrent database requests per pod.

Cloud Run / Cloud Functions likely both have better behavior here, as might KNative.
